### ISSUE TITLE
MAF-010: [HIGH] File upload insecurities

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#2234]
Several vulnerabilities were found within the file upload functionality:

* [x] Zip Slip (unsafe zip extraction) - paths are not restricted properly to safe extraction places. Validate and sanitize paths during extraction. #2258 
* [x] Race condition in directory existence checks - generate unique directory names for extraction. #2268
* [x] Lack of file type/size validation - implement strict validation. #2266 and #2267
