### ISSUE TITLE
Mesh analysis performance improvements

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#3203]
* [ ] Rewrite Mittsu STL loader in Rust
* [ ] Rewrite Mittsu OBJ loader in Rust
* [ ] (Re)write Mittsu 3MF loader in Rust
* [ ] Rewrite Mittsu mesh analysis in Rust
