### ISSUE TITLE
Full integration of federated content

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#3226]
Viewing federated content should be as simple as viewing content on your own Manyfold server.

* [x] [Define ActivityPub extensions for Manyfold-specific content types](https://manyfold.app/technology/activitypub)
  * [x] including FEP for universal acceptance of actor types https://codeberg.org/fediverse/fep/pulls/486/files
* Federate Manyfold-specific content fully via ActivityPub
  * [x] https://github.com/manyfold3d/manyfold/pull/3478
  * [x] #3479
  * [x] #3480
  * [x] #3502 
  * [x] #3508 
  * [x] #3507  
  * [x] #3509 
  * [x] #3491 
  * [x] #3511
  * [x] #3538 
  * [x] #3559
